### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by paulpach** [insthync/suriyun-unet-mmorpg#2]
I just bought your package version 1.0.4b,  imported it in a brand new unity project and replaced the project settings.

Right of the bat,  I get the following compilation issues in unity:

Unknown Property: 'CloudNetworkingId::CloudNetworkingId'.

Assets/SuriyunRPG/Scripts/Database/Handler/MySQLDatabaseHandler.cs(23,16): error CS0012: The type `System.Data.Common.DbConnection' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets/SuriyunRPG/Scripts/Database/Handler/MySQLDatabaseHandler.cs(510,51): error CS0012: The type `System.Data.IDataReader' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets/SuriyunRPG/Scripts/Database/Handler/MySQLDatabaseHandler.cs(510,51): error CS0012: The type `System.Data.IDataRecord' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by paulpach** [comment]
It is missing System.Data.dll,    I copied it from unity's mono and it seems good now.

Is this expected?

**Comment by insthync** [comment]
Yes, it is.

Seem like since Unity 5.5, the step that I explained (https://github.com/insthync/suriyun-unet-mmorpg/wiki/%5BError%5D-How-to-fix-Unhandled-Exception:-Mono.CSharpInternalErrorException:) is not enogh, we have to copy System.Data.dll from {UnityFolder}/Editor/Data/Mono/lib/mono/unity to the Plugins folder.

Next version I will include that dll files
